export const enum configServiceKeys {
  NODE_ENV = 'NODE_ENV',

  BACKEND_PORT = 'BACKEND_PORT',
  BACKEND_LINK = 'BACKEND_LINK',
  FRONTEND_LINK = 'FRONTEND_LINK',

  POSTGRES_PORT = 'POSTGRES_PORT',
  POSTGRES_DATABASE = 'POSTGRES_DATABASE',
  POSTGRES_HOSTNAME = 'POSTGRES_HOSTNAME',
  POSTGRES_USERNAME = 'POSTGRES_USERNAME',
  POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
  POSTGRES_AUTH_SOURCE = 'POSTGRES_AUTH_SOURCE',

  POSTGRES_SUPERADMIN_EMAIL = 'POSTGRES_SUPERADMIN_EMAIL',
  POSTGRES_SUPERADMIN_PASSWORD = 'POSTGRES_SUPERADMIN_PASSWORD',

  API_REQUEST_LIMIT = 'API_REQUEST_LIMIT',
  API_REFRESH_LIMIT_TIME = 'API_REFRESH_LIMIT_TIME',

  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
  JWT_EXPIRES_CONFIRMATIONS = 'JWT_EXPIRES_CONFIRMATIONS',
  JWT_SECRET = 'JWT_SECRET',

  ENCRYPTION_KEY = 'ENCRYPTION_KEY',

  ADMIN_MAIL = 'ADMIN_MAIL',
  MAILER_SENDER = 'MAILER_SENDER',
  MAILER_PASSWORD = 'MAILER_PASSWORD',
  MAILER_HOST = 'MAILER_HOST',
  MAILER_PORT = 'MAILER_PORT',
}
