export const enum configServiceKeys {
  NODE_ENV = 'NODE_ENV',

  BACKEND_PORT = 'BACKEND_PORT',
  BACKEND_LINK = 'BACKEND_LINK',
  FRONTEND_LINK = 'FRONTEND_LINK',

  API_REQUEST_LIMIT = 'API_REQUEST_LIMIT',
  API_REFRESH_LIMIT_TIME = 'API_REFRESH_LIMIT_TIME',
}
