export const enum configServiceKeys {
  NODE_ENV = 'NODE_ENV',

  BACKEND_PORT = 'BACKEND_PORT',
  BACKEND_LINK = 'BACKEND_LINK',
  FRONTEND_LINK = 'FRONTEND_LINK',

  MONGODB_PORT = 'MONGODB_PORT',
  MONGODB_DATABASE = 'MONGODB_DATABASE',
  MONGODB_HOSTNAME = 'MONGODB_HOSTNAME',
  MONGODB_USERNAME = 'MONGODB_USERNAME',
  MONGODB_PASSWORD = 'MONGODB_PASSWORD',
  MONGODB_AUTH_SOURCE = 'MONGODB_AUTH_SOURCE',

  MONGODB_SUPERADMIN_EMAIL = 'MONGODB_SUPERADMIN_EMAIL',
  MONGODB_SUPERADMIN_PASSWORD = 'MONGODB_SUPERADMIN_PASSWORD',

  API_REQUEST_LIMIT = 'API_REQUEST_LIMIT',
  API_REFRESH_LIMIT_TIME = 'API_REFRESH_LIMIT_TIME',

  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
  JWT_EXPIRES_CONFIRMATIONS = 'JWT_EXPIRES_CONFIRMATIONS',
  JWT_SECRET = 'JWT_SECRET',

  ENCRYPTION_KEY = 'ENCRYPTION_KEY',

  ADMIN_MAIL = 'ADMIN_MAIL',
  MAILER_SENDER = 'MAILER_SENDER',
  MAILER_PASSWORD = 'MAILER_PASSWORD',
  MAILER_HOST = 'MAILER_HOST',
  MAILER_PORT = 'MAILER_PORT',
}
